# Generated by Django 5.1.2 on 2024-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_doctor_dr_pwd_hospital_hosp_pwd_patient_pat_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$uiFuOna4kzdhOclFpu1fxh$psWDVidtaXJDhKIDXbO93i0Diy+ROBMUykQqJxUNlHQ=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$chJFaKJ8iOr8dnGjKaIZpO$Ei8RVA33BX2OkYldh1VUE7VbbTfmMEl9dLc2SWqJR8A=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$G0LVYq5TaNaAB4B5SihXea$m5fQ5bRwfTi10hwAMFMe7/Tdtpf+qM8bbg/iVSElE8c=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$iHN6NDfEPPyXVz2mvlBbvN$V1oTinLpC7mpsv1Y7L0JOWBNnVKtpRWpvcw/GpkrE8A=', max_length=128),
        ),
    ]
