# Generated by Django 5.1.2 on 2024-10-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_doctor_dr_pwd_alter_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$A5Uiq2EsO3T6SQHnK9oopL$JOx107bluI76KsGguAwkOp9OtCPMa4axTvkchH5q2tU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$BNHjUXvZB63SM5xIebvaIU$ObZG6p3IEtUu3FsJQibJ8hGhrlsytfwujwrmAaSGQL4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$pf2FBzwHVbqq8WPfOz9Upw$e8JV2Dls+4JloDct1o7JcSxMO8G5JXYkFNoZKWXg0QU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$u69kjFAvda5tK5wgDke0cD$xeQRBOMKRhZ2JOKTHDAFUiqi9/3FfJCakDedp/VVng4=', max_length=128),
        ),
    ]
