# Generated by Django 5.1.2 on 2024-10-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_doctor_dr_pwd_alter_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dr_pwd',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='hosp_pwd',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pat_pwd',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_pwd',
        ),
    ]
