# Generated by Django 5.1.2 on 2024-10-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_remove_doctor_dr_pwd_remove_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$TBr4DEkClXE5WVqgrru7JY$amw7A25h+MuNS6PUob7SkMAmPB4VgqHQYZHhf6hKLRE=', max_length=128),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$itYkjfHbX1Vy4JfPx4GeyZ$WnkyaRbm1A9Gncczfuz+PHQEGlvZaypDb1EjeOjBZdg=', max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$WJIBzamkVWt5GmHygRpmVL$aOQiQGcTbIOMyaT+tpDejgrOpz8VHP/O7O8YPJI/psI=', max_length=128),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$oZJ9zoNLlid9mGAsU6pvsF$dQlLN8RR6E82tafblbjmc1V+yBqdTQG/DlTvQmwoZQk=', max_length=128),
        ),
    ]
