# Generated by Django 5.1.2 on 2024-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_doctor_dr_pwd_hospital_hosp_pwd_patient_pat_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_phno',
            field=models.CharField(max_length = 15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$LpRGEl3lkAq9wmL2Qv9hFB$b9uXRtEXd7iTy0Cr1VVGq8qm55GYIgjLg0QccTCydZ8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$F2PbhLHVCx96DNnEkIV91U$t4HMLoAWYf1b6J35PIoD4z3/vHQ5vQCe/ifEtWKu81M=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_phno',
            field=models.CharField(max_length = 15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_phno',
            field=models.CharField(max_length = 15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$hsPOrIRwylSOMTBnXTCLPM$OWbbTmuSzsS1hSGJVvcslBPEv28eIND+xhDe/4aVybs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phno',
            field=models.CharField(max_length = 15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$un2K0GttdJsIOykqEHWo4U$D8RZO/GYhGFihT64UBj7nZfUutQXE2rMcLkcTTMaPKE=', max_length=128),
        ),
    ]
