# Generated by Django 5.1.2 on 2024-10-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_alter_doctor_dr_phno_alter_doctor_dr_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$Kdnmoqz2GXze2ij5Ijghuy$D2dDm8ToDr53OuAHBTjP+7GIs4R3KzcLQmtYdACQZ20=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$yzsCEOxbb1PMFVaAqaRKEg$v2ribKQBEcZfBLK5paFizBA3vTnpbNi3TcNzbveJVrA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$RZpFL1ZGI1bcIhuihyk2aC$dGaLDOOddnvF5BgYDus6riVHTIrQ+bZRZ8EBspIQREE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phno',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$EKdS8UC73ogFufVnypWYpK$Y11HkVSfcYlPuUSXPURrFEpmeWNBVzgFt5LAJ6lPlcY=', max_length=128),
        ),
    ]
