# Generated by Django 5.1.2 on 2024-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_alter_doctor_dr_phno_alter_doctor_dr_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$jUWfJcotwMwR3vNkH5gLhD$twEl6C6qI+QzxoR0vrTMl1qjK0l/iDOjrw7+ChqpVJc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$f6m0aurEQjgfbnzBbtY5ix$rcGOr+Rw9iz+A8SyZvHS+CwbUI6zXsHOZ3TAX0H+zMg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$dC0VgcSS6WKJqgqcZA2Om2$aC4b1YdLJdJnBwgGYOP2M/iUIETNU7fo5SD98rv7KMc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$E2ntLwj5yi9IZWw1Xr57X2$SZcHX9yp2V5nVlZYxvTu4Jt9R4zfBcv3f4qOyDi3LeE=', max_length=128),
        ),
    ]
