# Generated by Django 5.1.2 on 2024-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_alter_doctor_dr_pwd_alter_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$sLwr4ff1SoY1wt5M88SbJF$vDWwXCN/+qrEe6Mkp5/cUyjg/uqnz3/afpvZmtQVssU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$mqsdRShuz79kb4rMax0Ktx$2nQlrZBQ3LvzTGr7XL9liayDonquR82l9Q5tqY0hpTs=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$YXGx0HfnVPRyEU3IUdaGvD$g/97dTCayDfHTlWmMXYcaY6uDQz0h69NHKwqVCYAOCA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$EiuHmwz0pre1wOTa8SUyPO$qmhPLUo+NSNVcNwDB+6Y6xJBe7aHkZJpOUY24PSfWQA=', max_length=128),
        ),
    ]
