# Generated by Django 5.1.2 on 2024-10-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_alter_doctor_dr_phno_alter_doctor_dr_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_phno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$MEkyfFGWbdsLhnBy3SpIZo$ehzi7P+yHOMt4MVxTGXsUoDPZdIsqnUSZjdUtUYiJGk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$E9oXuVhY35rRqK6qAjqC45$j/BIruPLUJ77odiP9itU8rdKnNxFY2s7e1hPK0UgeuI=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_phno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_phno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$ul1PREzS9srbf2LhqFWly2$m2mxUo1Cs0UP+VC36VL/HQZddDWdclEmN98by8CzWsk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_phno',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$Mma4OwgyuGSHRjct7lsnDO$VHu2HaA1xI0F14q2E7xDuiawl/99TKiraYQ1J0zwCuM=', max_length=128),
        ),
    ]
