# Generated by Django 5.1.2 on 2024-10-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0014_alter_doctor_dr_phno_alter_doctor_dr_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$gL7pjT0xIOE05UrqEkJVnL$T8OBLuSMXmSXj1marGvE6MMNmOVjGm1qhuGb4GZuofA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$MkMpSs95jwMmBXd0mZP7tD$fUWwewayn94SxTIQn3eo+HYV/oMFbqGgIS1xO5PIiUg=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$jPYzeG2fkf33sWcsNjAWSh$cL9TOCb8Tl8YNL8nQHQ+uEm/EU8c1+5+2oL3XBXPbyo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$SpJIJntqHoJlcUAKMvqxhO$Sa0zuFZlDYQppNJiyRLSwzknSEc0TmQI8eU0kFd6DPE=', max_length=128),
        ),
    ]
