# Generated by Django 5.1.2 on 2024-10-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0016_alter_doctor_dr_pwd_alter_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$Lvmghh9GRFz7cdvWMRKUFY$os8UZEYd6Ysi+u3NyMpcyTboy9nACpGXvvxKu4ZOxDk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$ta4PiX9hTw4Q1qmO7VPBL0$z7vcEELbuGgS9aInQ/6dyzgKaO2oZrXPCBExiUWqmlc=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$JG4vMYjItJFcA2t4jCoEPZ$hCZCJloEMaiatROIF6XEXNclYyI50SEXBTZUAQ4dMaE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$UvGM3xSIKrFxf5gWwkwpvq$ZfKpYvU+Qz7TSUMQEG8dgu34tsjMsms8lcI9GISfk9A=', max_length=128),
        ),
    ]
