# Generated by Django 5.1.2 on 2024-10-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0017_alter_doctor_dr_pwd_alter_hospital_hosp_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dr_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$aFYSk6xAvXmoHKui2w1l9x$+RWfte2r9CRjxJYJOFXlBgKOH5eC+YGmvmVRdwqXal4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hosp_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$8rkqU2eVlRAJazUrLqgCEb$bTIrBSf75Xfby/+Zq9b4E6yf+5n7oZBx/YIUlpDa3J4=', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$5SmsmuX4yAbe1G9BEAoZ3k$ZfOUaa4jKGI7RyY0H73ZXW9euxSgUIsuE7j8NB4kKGA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_pwd',
            field=models.CharField(default='pbkdf2_sha256$870000$sUpn4zD92JafnUgHAleNM0$9jYHMxslskGgmsx5sJ/4KcJmw7CR8zjjAaMxltuL7uI=', max_length=128),
        ),
    ]
